<?xml version="1.0" encoding="utf-8"?><Database Name="Monster_Sport" Class="MappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberOfTeams" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinPlayers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fee" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Tax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Game_TeamsForGame" Member="TeamsForGames" ThisKey="Id" OtherKey="GameID" Type="TeamsForGame" />
      <Association Name="Game_Ticket" Member="Tickets" ThisKey="Id" OtherKey="GameID" Type="Ticket" />
      <Association Name="Game_Winner" Member="Winners" ThisKey="Id" OtherKey="GameID" Type="Winner" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Movement" Member="Movements" ThisKey="Id" OtherKey="UserID" Type="Movement" />
      <Association Name="User_Payment" Member="Payments" ThisKey="Id" OtherKey="UserID" Type="Payment" />
      <Association Name="User_Ticket" Member="Tickets" ThisKey="Id" OtherKey="UserID" Type="Ticket" />
      <Association Name="User_Winner" Member="Winners" ThisKey="Id" OtherKey="UserID" Type="Winner" />
    </Type>
  </Table>
  <Table Name="dbo.Team" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Team_TeamsForGame" Member="TeamsForGames" ThisKey="Id" OtherKey="TeamID" Type="TeamsForGame" />
      <Association Name="Team_TicketResult" Member="TicketResults" ThisKey="Id" OtherKey="TeamID" Type="TicketResult" />
    </Type>
  </Table>
  <Table Name="dbo.Movement" Member="Movements">
    <Type Name="Movement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Movement" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOfPay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PaypalTransition" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Payment" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TeamsForGame" Member="TeamsForGames">
    <Type Name="TeamsForGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TeamsForGame_Result" Member="Results" ThisKey="Id" OtherKey="TeamForGameID" Type="Result" />
      <Association Name="Game_TeamsForGame" Member="Game" ThisKey="GameID" OtherKey="Id" Type="Game" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Team_TeamsForGame" Member="Team" ThisKey="TeamID" OtherKey="Id" Type="Team" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GetDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Ticket_TicketResult" Member="TicketResults" ThisKey="Id" OtherKey="TicketID" Type="TicketResult" />
      <Association Name="Game_Ticket" Member="Game" ThisKey="GameID" OtherKey="Id" Type="Game" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_Ticket" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Result" Member="Results">
    <Type Name="Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamForGameID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoundNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Result" Member="Result1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TeamsForGame_Result" Member="TeamsForGame" ThisKey="TeamForGameID" OtherKey="Id" Type="TeamsForGame" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Winner" Member="Winners">
    <Type Name="Winner">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prize" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WinDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Game_Winner" Member="Game" ThisKey="GameID" OtherKey="Id" Type="Game" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="User_Winner" Member="User" ThisKey="UserID" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TicketResult" Member="TicketResults">
    <Type Name="TicketResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoundNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Team_TicketResult" Member="Team" ThisKey="TeamID" OtherKey="Id" Type="Team" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Ticket_TicketResult" Member="Ticket" ThisKey="TicketID" OtherKey="Id" Type="Ticket" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>